server.port=5432
spring.application.name=mine-sentinel-backend
spring.thymeleaf.cache=false

#          CONFIGURACIÓN DE CONEXIÓN POSTGRESQL (SUPABASE)
spring.datasource.url=jdbc:postgresql://${DB_HOST:db.dbimdevutkrsajxgseyu.supabase.co}:${DB_PORT:6543}/${DB_NAME:postgres}?sslmode=require&prepareThreshold=0
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Ramiropt12345%}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.keepalive-time=45000
spring.datasource.hikari.pool-name=MineSentinelHikariPool

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

minesentinel.aforo.maximo=50
minesentinel.aforo.minimo=10
minesentinel.aforo.umbral-critico=90
minesentinel.browser.auto-launch=true

